name: Build

on:
  workflow_call:

permissions:
  contents: read

env:
  HOMEBREW_DEVELOPER: 1
  HOMEBREW_NO_AUTO_UPDATE: 1
  HOMEBREW_ARM64_TESTING: 1

jobs:
  build:
    strategy:
      matrix:
        include:
          - image: macos-13-xlarge
            arch: arm64-macos13
          - image: macos-13
            arch: x86_64-macos13
          - image: macos-14
            arch: arm64-macos14
          - image: macos-14-large
            arch: x86_64-macos14
          - image: macos-15
            arch: arm64-macos15
          - image: macos-15-large
            arch: x86_64-macos15
          - image: ubuntu-22.04
            arch: x86_64-linux-gnu235
          - image: ubuntu-22.04-arm
            arch: aarch64-linux-gnu235
      fail-fast: false
    runs-on: ${{matrix.image}}
    defaults:
      run:
        working-directory: ${{github.workspace}}
    steps:
      - uses: actions/checkout@main
      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo "/home/linuxbrew/.linuxbrew/bin" >> $GITHUB_PATH
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew tap spinel-coop/rv-ruby .

      - name: Build Portable Ruby
        run: |
          mkdir -p bottle/
          cd bottle
          brew portable-package --verbose portable-ruby

      - name: Upload Portable Ruby
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: bottles_${{matrix.arch}}
          path: ${{github.workspace}}/bottle

      - name: Test Portable Ruby
        run: |
          mkdir -p portable-ruby/
          tar --strip-components 2 -C portable-ruby -xf bottle/portable-ruby--*.tar.gz
          export PATH="${PWD}/portable-ruby/bin:${PATH}"
          export HOMEBREW_USE_RUBY_FROM_PATH=1
          rm -rf "$(brew --repo)/Library/Homebrew/vendor/portable-ruby"
          brew config | awk -v s="${PWD}/portable-ruby/bin/ruby" '$0~s{r=1} 1; END{exit(!r)}'
